azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    instance_type: Standard_D1_v2
- name: large
  cloud_properties:
    instance_type: Standard_D2_v2
- name: xlarge
  cloud_properties:
    instance_type: Standard_D3_v2
- name: xxlarge
  cloud_properties:
    instance_type: Standard_D4_v2

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((director_cidr))
    gateway: ((director_gw))
    azs: [z1, z2, z3]
    dns: [((director_dns))]
    reserved: [((director_gw))/29]
    cloud_properties:
      virtual_network_name: ((azure_vnet_name))
      subnet_name: ((azure_subnet_name))
      security_group: ((azure_nsg))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
