azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z2
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z3
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 4096
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 32_768
- name: xlarge
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 131_072

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((director_cidr))
    gateway: ((director_gw))
    azs: [z1, z2, z3]
    dns: [((director_dns))]
    reserved: ((network_reserved_ips))
    static: ((network_static_ips))
    cloud_properties:
      name: ((network_name))

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
